source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, '9.2'

pod 'AFNetworking', '~> 3.0'
pod 'FlickrKit'
pod 'XCDYouTubeKit', '~> 2.5'

#pod 'RSSAtomKit', :git => 'https://github.com/chrisballinger/RSSAtomKit.git'